version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/aws-lambda-node-starter"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/aws-lambda-node-java-starter/node-backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/aws-lambda-java-starter"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/aws-lambda-node-java-starter/java-backend"
    schedule:
      interval: "weekly"
